import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/Card";
import { AlertTriangle, Shield, TrendingDown, AlertCircle, ArrowRight } from 'lucide-react';
import { Button } from "./ui/Button";
import { Progress } from "./ui/Progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/Tabs";

export function RiskAnalyzer() {
  // In a real app, this would be generated by your AI analysis
  const contractRisks = [
    {
      id: 1,
      clause: "Section 12.3 - Termination for Convenience",
      risk: "Agency can terminate contract at any time with 15 days notice",
      severity: "high",
      recommendation: "Request 30-day notice period and partial compensation for termination costs"
    },
    {
      id: 2,
      clause: "Section 8.2 - Intellectual Property Rights",
      risk: "All work products, including pre-existing IP, become government property",
      severity: "high",
      recommendation: "Negotiate to retain rights to pre-existing IP with government receiving license"
    },
    {
      id: 3,
      clause: "Section 14.5 - Liquidated Damages",
      risk: "$5,000 per day for missed milestones without force majeure exceptions",
      severity: "medium",
      recommendation: "Add force majeure clause and cap liquidated damages at 10% of contract value"
    },
    {
      id: 4,
      clause: "Section 10.1 - Payment Terms",
      risk: "Net-60 payment terms may cause cash flow issues",
      severity: "medium",
      recommendation: "Request Net-30 payment terms or progress payments tied to milestones"
    },
    {
      id: 5,
      clause: "Section 16.3 - Indemnification",
      risk: "Broad indemnification without monetary cap",
      severity: "high",
      recommendation: "Limit indemnification to direct damages with cap at contract value"
    },
    {
      id: 6,
      clause: "Section 9.4 - Service Level Agreements",
      risk: "99.99% uptime requirement with steep penalties",
      severity: "medium",
      recommendation: "Tier the SLAs with different penalty structures for critical vs. non-critical services"
    },
    {
      id: 7,
      clause: "Section 15.2 - Insurance Requirements",
      risk: "Cyber liability insurance requirement of $10M exceeds current policy",
      severity: "low",
      recommendation: "Request reduction to $5M or phase-in approach as contract progresses"
    }
  ];

  const riskSeverityCounts = {
    high: contractRisks.filter(r => r.severity === "high").length,
    medium: contractRisks.filter(r => r.severity === "medium").length,
    low: contractRisks.filter(r => r.severity === "low").length
  };

  return (
    <Card className="mt-4">
      <CardHeader>
        <CardTitle className="flex items-center">
          <AlertTriangle className="h-5 w-5 mr-2" />
          Contract Risk Analysis
        </CardTitle>
        <CardDescription>
          AI-identified contract risks and recommended mitigation strategies
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <Card className="border-red-200 dark:border-red-900">
            <CardContent className="p-4 flex items-center">
              <div className="h-10 w-10 rounded-full bg-red-100 dark:bg-red-900/20 flex items-center justify-center mr-3">
                <AlertCircle className="h-6 w-6 text-red-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{riskSeverityCounts.high}</p>
                <p className="text-sm text-muted-foreground">High Severity Risks</p>
              </div>
            </CardContent>
          </Card>
          <Card className="border-amber-200 dark:border-amber-900">
            <CardContent className="p-4 flex items-center">
              <div className="h-10 w-10 rounded-full bg-amber-100 dark:bg-amber-900/20 flex items-center justify-center mr-3">
                <AlertCircle className="h-6 w-6 text-amber-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{riskSeverityCounts.medium}</p>
                <p className="text-sm text-muted-foreground">Medium Severity Risks</p>
              </div>
            </CardContent>
          </Card>
          <Card className="border-blue-200 dark:border-blue-900">
            <CardContent className="p-4 flex items-center">
              <div className="h-10 w-10 rounded-full bg-blue-100 dark:bg-blue-900/20 flex items-center justify-center mr-3">
                <AlertCircle className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{riskSeverityCounts.low}</p>
                <p className="text-sm text-muted-foreground">Low Severity Risks</p>
              </div>
            </CardContent>
          </Card>
        </div>

        <Tabs defaultValue="high">
          <TabsList className="grid w-full grid-cols-3 mb-4">
            <TabsTrigger value="high">High Risks</TabsTrigger>
            <TabsTrigger value="medium">Medium Risks</TabsTrigger>
            <TabsTrigger value="low">Low Risks</TabsTrigger>
          </TabsList>

          <TabsContent value="high">
            <div className="space-y-4">
              {contractRisks.filter(risk => risk.severity === "high").map((risk) => (
                <Card key={risk.id} className="border-red-200 dark:border-red-900">
                  <CardContent className="p-4">
                    <h3 className="font-medium mb-1">{risk.clause}</h3>
                    <p className="text-sm text-muted-foreground mb-3">{risk.risk}</p>
                    <div className="bg-red-50 dark:bg-red-950/20 p-3 rounded-md flex gap-2">
                      <ArrowRight className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                      <p className="text-sm"><span className="font-medium">Recommendation:</span> {risk.recommendation}</p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="medium">
            <div className="space-y-4">
              {contractRisks.filter(risk => risk.severity === "medium").map((risk) => (
                <Card key={risk.id} className="border-amber-200 dark:border-amber-900">
                  <CardContent className="p-4">
                    <h3 className="font-medium mb-1">{risk.clause}</h3>
                    <p className="text-sm text-muted-foreground mb-3">{risk.risk}</p>
                    <div className="bg-amber-50 dark:bg-amber-950/20 p-3 rounded-md flex gap-2">
                      <ArrowRight className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                      <p className="text-sm"><span className="font-medium">Recommendation:</span> {risk.recommendation}</p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="low">
            <div className="space-y-4">
              {contractRisks.filter(risk => risk.severity === "low").map((risk) => (
                <Card key={risk.id} className="border-blue-200 dark:border-blue-900">
                  <CardContent className="p-4">
                    <h3 className="font-medium mb-1">{risk.clause}</h3>
                    <p className="text-sm text-muted-foreground mb-3">{risk.risk}</p>
                    <div className="bg-blue-50 dark:bg-blue-950/20 p-3 rounded-md flex gap-2">
                      <ArrowRight className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                      <p className="text-sm"><span className="font-medium">Recommendation:</span> {risk.recommendation}</p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>
        </Tabs>

        <div className="mt-6 flex gap-4">
          <Button>Generate Risk Report</Button>
          <Button variant="outline">Prepare Contract Amendment Suggestions</Button>
        </div>
      </CardContent>
    </Card>
  );
}
